export { default as MCheckbox } from './MCheckbox.vue'
export { default as MInput } from './MInput.vue'
export { default as MInputNumber } from './InputNumber.vue'
export { default as MSwitch } from './MSwitch.vue'
export { default as MSelect } from './MSelect.vue'
